services:
  - type: web
    name: festival-combo-builder
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: POSTGRES_URI
        sync: false
